# Use the official Go image as the base image
FROM golang:latest

# Set the working directory inside the container
WORKDIR /awesomeProject

# Copy the Go application source code into the container
COPY . .

# Build the Go application inside the container
RUN go build -o main

# Expose the port your application will listen on
EXPOSE 8080

# Define the command to run your application
CMD ["./main"]